version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/elb-test
hooks:
  ApplicationStop:
    - location: stop_httpd.sh
    - location: scripts/deregister_from_elb.sh
       timeout: 180
  ApplicationStart:
    - location: start_httpd.sh
    - location: scripts/register_with_elb.sh
       timeout: 180
